/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iggyDex from "./IGGY Dex";
export * as iggyToken from "./IGGY Token";
export * as lfjForReference from "./LFJ (for reference)";
export * as postPuppetMint from "./PostPuppetMint";
export * as puppets from "./Puppets";
export * as test from "./test";
