/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as joePairSol from "./JoePair.sol";
export type { joePairSol };
export type { IERC20Joe } from "./IERC20Joe";
export type { IJoeCallee } from "./IJoeCallee";
export type { IJoeFactory } from "./IJoeFactory";
export type { JoeERC20 } from "./JoeERC20";
export type { JoeFactory } from "./JoeFactory";
