/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DonationContract } from "./DonationContract";
export type { IERC8004 } from "./IERC8004";
export type { INodeRegistry } from "./INodeRegistry";
