[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
