/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PuppetDropperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "airDropSingle"
      | "airDropTwoForOne"
      | "executeAirdrop"
      | "puppets"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "airDropSingle",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "airDropTwoForOne",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeAirdrop",
    values: [BigNumberish, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "puppets", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "airDropSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "airDropTwoForOne",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeAirdrop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "puppets", data: BytesLike): Result;
}

export interface PuppetDropper extends BaseContract {
  connect(runner?: ContractRunner | null): PuppetDropper;
  waitForDeployment(): Promise<this>;

  interface: PuppetDropperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  airDropSingle: TypedContractMethod<
    [recipient: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  airDropTwoForOne: TypedContractMethod<
    [startTokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeAirdrop: TypedContractMethod<
    [
      startTokenId: BigNumberish,
      presaleAddresses: AddressLike[],
      preSaleNumToDrop: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  puppets: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "airDropSingle"
  ): TypedContractMethod<
    [recipient: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "airDropTwoForOne"
  ): TypedContractMethod<[startTokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeAirdrop"
  ): TypedContractMethod<
    [
      startTokenId: BigNumberish,
      presaleAddresses: AddressLike[],
      preSaleNumToDrop: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "puppets"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
