/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DonationTracker {
  export type DonationStruct = {
    id: BigNumberish;
    donationId: string;
    donor: AddressLike;
    projectAddress: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
    projectName: string;
    companyName: string;
    verified: boolean;
  };

  export type DonationStructOutput = [
    id: bigint,
    donationId: string,
    donor: string,
    projectAddress: string,
    amount: bigint,
    timestamp: bigint,
    projectName: string,
    companyName: string,
    verified: boolean
  ] & {
    id: bigint;
    donationId: string;
    donor: string;
    projectAddress: string;
    amount: bigint;
    timestamp: bigint;
    projectName: string;
    companyName: string;
    verified: boolean;
  };
}

export interface DonationTrackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "OPERATOR_ROLE"
      | "donationIdToIndex"
      | "donations"
      | "donorDonations"
      | "getDonationById"
      | "getDonationsByDonor"
      | "getDonationsPaginated"
      | "getProjectTotal"
      | "getRoleAdmin"
      | "getTotalStats"
      | "grantOperatorRole"
      | "grantRole"
      | "hasRole"
      | "pause"
      | "paused"
      | "projectTotalReceived"
      | "recordDonation"
      | "renounceRole"
      | "revokeOperatorRole"
      | "revokeRole"
      | "supportsInterface"
      | "totalAmountTracked"
      | "totalDonationsTracked"
      | "unpause"
      | "verifyDonation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DonationRecorded"
      | "DonationVerified"
      | "Paused"
      | "ProjectFunded"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "donationIdToIndex",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "donations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "donorDonations",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDonationById",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDonationsByDonor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDonationsPaginated",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectTotal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantOperatorRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "projectTotalReceived",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordDonation",
    values: [string, AddressLike, AddressLike, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeOperatorRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAmountTracked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalDonationsTracked",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyDonation",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "donationIdToIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donations", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "donorDonations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonationById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonationsByDonor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonationsPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantOperatorRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "projectTotalReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordDonation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeOperatorRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAmountTracked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDonationsTracked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyDonation",
    data: BytesLike
  ): Result;
}

export namespace DonationRecordedEvent {
  export type InputTuple = [
    id: BigNumberish,
    donationId: string,
    donor: AddressLike,
    projectAddress: AddressLike,
    amount: BigNumberish,
    projectName: string,
    companyName: string
  ];
  export type OutputTuple = [
    id: bigint,
    donationId: string,
    donor: string,
    projectAddress: string,
    amount: bigint,
    projectName: string,
    companyName: string
  ];
  export interface OutputObject {
    id: bigint;
    donationId: string;
    donor: string;
    projectAddress: string;
    amount: bigint;
    projectName: string;
    companyName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DonationVerifiedEvent {
  export type InputTuple = [id: BigNumberish, donationId: string];
  export type OutputTuple = [id: bigint, donationId: string];
  export interface OutputObject {
    id: bigint;
    donationId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectFundedEvent {
  export type InputTuple = [projectAddress: AddressLike, amount: BigNumberish];
  export type OutputTuple = [projectAddress: string, amount: bigint];
  export interface OutputObject {
    projectAddress: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DonationTracker extends BaseContract {
  connect(runner?: ContractRunner | null): DonationTracker;
  waitForDeployment(): Promise<this>;

  interface: DonationTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  donationIdToIndex: TypedContractMethod<[arg0: string], [bigint], "view">;

  donations: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        boolean
      ] & {
        id: bigint;
        donationId: string;
        donor: string;
        projectAddress: string;
        amount: bigint;
        timestamp: bigint;
        projectName: string;
        companyName: string;
        verified: boolean;
      }
    ],
    "view"
  >;

  donorDonations: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getDonationById: TypedContractMethod<
    [donationId: string],
    [DonationTracker.DonationStructOutput],
    "view"
  >;

  getDonationsByDonor: TypedContractMethod<
    [donor: AddressLike],
    [bigint[]],
    "view"
  >;

  getDonationsPaginated: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [DonationTracker.DonationStructOutput[]],
    "view"
  >;

  getProjectTotal: TypedContractMethod<
    [projectAddress: AddressLike],
    [bigint],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTotalStats: TypedContractMethod<
    [],
    [[bigint, bigint] & { totalDonations: bigint; totalAmount: bigint }],
    "view"
  >;

  grantOperatorRole: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  projectTotalReceived: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  recordDonation: TypedContractMethod<
    [
      donationId: string,
      donor: AddressLike,
      projectAddress: AddressLike,
      amount: BigNumberish,
      projectName: string,
      companyName: string
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeOperatorRole: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalAmountTracked: TypedContractMethod<[], [bigint], "view">;

  totalDonationsTracked: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verifyDonation: TypedContractMethod<
    [donationId: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "donationIdToIndex"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "donations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        boolean
      ] & {
        id: bigint;
        donationId: string;
        donor: string;
        projectAddress: string;
        amount: bigint;
        timestamp: bigint;
        projectName: string;
        companyName: string;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "donorDonations"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDonationById"
  ): TypedContractMethod<
    [donationId: string],
    [DonationTracker.DonationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDonationsByDonor"
  ): TypedContractMethod<[donor: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getDonationsPaginated"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [DonationTracker.DonationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProjectTotal"
  ): TypedContractMethod<[projectAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalStats"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { totalDonations: bigint; totalAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantOperatorRole"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "projectTotalReceived"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordDonation"
  ): TypedContractMethod<
    [
      donationId: string,
      donor: AddressLike,
      projectAddress: AddressLike,
      amount: BigNumberish,
      projectName: string,
      companyName: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeOperatorRole"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalAmountTracked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalDonationsTracked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyDonation"
  ): TypedContractMethod<[donationId: string], [void], "nonpayable">;

  getEvent(
    key: "DonationRecorded"
  ): TypedContractEvent<
    DonationRecordedEvent.InputTuple,
    DonationRecordedEvent.OutputTuple,
    DonationRecordedEvent.OutputObject
  >;
  getEvent(
    key: "DonationVerified"
  ): TypedContractEvent<
    DonationVerifiedEvent.InputTuple,
    DonationVerifiedEvent.OutputTuple,
    DonationVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectFunded"
  ): TypedContractEvent<
    ProjectFundedEvent.InputTuple,
    ProjectFundedEvent.OutputTuple,
    ProjectFundedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "DonationRecorded(uint256,string,address,address,uint256,string,string)": TypedContractEvent<
      DonationRecordedEvent.InputTuple,
      DonationRecordedEvent.OutputTuple,
      DonationRecordedEvent.OutputObject
    >;
    DonationRecorded: TypedContractEvent<
      DonationRecordedEvent.InputTuple,
      DonationRecordedEvent.OutputTuple,
      DonationRecordedEvent.OutputObject
    >;

    "DonationVerified(uint256,string)": TypedContractEvent<
      DonationVerifiedEvent.InputTuple,
      DonationVerifiedEvent.OutputTuple,
      DonationVerifiedEvent.OutputObject
    >;
    DonationVerified: TypedContractEvent<
      DonationVerifiedEvent.InputTuple,
      DonationVerifiedEvent.OutputTuple,
      DonationVerifiedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ProjectFunded(address,uint256)": TypedContractEvent<
      ProjectFundedEvent.InputTuple,
      ProjectFundedEvent.OutputTuple,
      ProjectFundedEvent.OutputObject
    >;
    ProjectFunded: TypedContractEvent<
      ProjectFundedEvent.InputTuple,
      ProjectFundedEvent.OutputTuple,
      ProjectFundedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
