/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IMasterChef {
  export type PoolInfoStruct = {
    lpToken: AddressLike;
    allocPoint: BigNumberish;
    lastRewardTimestamp: BigNumberish;
    accJoePerShare: BigNumberish;
  };

  export type PoolInfoStructOutput = [
    lpToken: string,
    allocPoint: bigint,
    lastRewardTimestamp: bigint,
    accJoePerShare: bigint
  ] & {
    lpToken: string;
    allocPoint: bigint;
    lastRewardTimestamp: bigint;
    accJoePerShare: bigint;
  };
}

export interface IMasterChefInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deposit"
      | "devPercent"
      | "investorPercent"
      | "joePerSec"
      | "poolInfo"
      | "totalAllocPoint"
      | "treasuryPercent"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "devPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "investorPercent",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "joePerSec", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAllocPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryPercent",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "devPercent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "investorPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joePerSec", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAllocPoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryPercent",
    data: BytesLike
  ): Result;
}

export interface IMasterChef extends BaseContract {
  connect(runner?: ContractRunner | null): IMasterChef;
  waitForDeployment(): Promise<this>;

  interface: IMasterChefInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deposit: TypedContractMethod<
    [_pid: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  devPercent: TypedContractMethod<[], [bigint], "view">;

  investorPercent: TypedContractMethod<[], [bigint], "view">;

  joePerSec: TypedContractMethod<[], [bigint], "view">;

  poolInfo: TypedContractMethod<
    [pid: BigNumberish],
    [IMasterChef.PoolInfoStructOutput],
    "view"
  >;

  totalAllocPoint: TypedContractMethod<[], [bigint], "view">;

  treasuryPercent: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [_pid: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "devPercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "investorPercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "joePerSec"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "poolInfo"
  ): TypedContractMethod<
    [pid: BigNumberish],
    [IMasterChef.PoolInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalAllocPoint"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "treasuryPercent"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
