/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IJoeFactory,
  IJoeFactoryInterface,
} from "../../../../contracts/IGGY Token/IJoe.sol/IJoeFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
    ],
    name: "createPair",
    outputs: [
      {
        internalType: "address",
        name: "pair",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IJoeFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IJoeFactoryInterface {
    return new Interface(_abi) as IJoeFactoryInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IJoeFactory {
    return new Contract(address, _abi, runner) as unknown as IJoeFactory;
  }
}
