/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
export type { IERC20 } from "./IERC20";
export type { Isbjorn } from "./Isbjorn";
export type { Ownable } from "./Ownable";
