/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IIcePondFactory } from "./IIcePondFactory";
export type { IIsbjorn2Router } from "./IIsbjorn2Router";
export type { IIsbjornRouter } from "./IIsbjornRouter";
