/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iggyDex from "./IGGY Dex";
export type { iggyDex };
import type * as iggyToken from "./IGGY Token";
export type { iggyToken };
import type * as lfjForReference from "./LFJ (for reference)";
export type { lfjForReference };
import type * as test from "./test";
export type { test };
